import "../styles/globals.css";
import "react-toastify/dist/ReactToastify.min.css";
import Toastify from "./Toastify";
function RootLayout({ children }) {
  return (
    <html>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="bg-[#051139]">
        <>
          {children}
          <Toastify />
        </>
      </body>
    </html>
  );
}

export default RootLayout;
