import "../styles/globals.css";
import Providers from "./Providers";

export default function RootLayout({ children }) {
  return (
    <html>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="bg-slate-300">{children}</body>
    </html>
  );
}
