"use client";

import "../styles/globals.css";
import dynamic from "next/dynamic";
import { ReactNode } from "react";
import NoInternetConnection from "./NoInternetConnection";
const Toastify = dynamic(() => import("./Toastify"));
function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={"bg-[#051139]"}>
        <NoInternetConnection>
          {children}
          <Toastify />
        </NoInternetConnection>
      </body>
    </html>
  );
}

export default RootLayout;
